import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Addition from './sums/addition'
import Subtraction from './sums/subtraction'
import Multiplication from './sums/multiplication'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1>Basic calculator</h1>
      <Link href="/sums/addition" className='Link'>Addition</Link>
      <Link href="/sums/subtraction" className='Link'>Subtraction</Link>
      <Link href="/sums/multiplication" className='Link'>Multiplication</Link>

      {/* <Addition/>
      <Subtraction/>
      <Multiplication/> */}
      </main>
    </div>
  )
}
